### PR TITLE
Make it numa-enabled

### PR DESCRIPTION
**Pull request by grossws**
Add numactl to image and `docker-entrypoint.sh` script.

### CODE REVIEW

**Comment by henrjk** [comment]
I just started using the image (`docker pull mongo:2.6`) but when I run it it exits immediately:
```
dev$ docker run --name some-mongo -d mongo
dev$ docker inspect some-mongo | grep -i "exit"
        "ExitCode": 1,
```

When I start the image with bash instead 
```
dev$docker run -ti mongo /bin/bash 
```
and then inside the container execute commands from [entrypoint.sh](https://github.com/docker-library/mongo/blob/master/2.6/docker-entrypoint.sh) I see that the system does not support NUMA policy: 

```
root@8530e8ebaa71:/# chown -R mongodb /data/db
root@8530e8ebaa71:/# gosu mongodb numactl --interleave=all mongod
numactl: This system does not support NUMA policy
```

This is on a dev machine using docker 1.3.0 (build c78088f) on a MacBook Pro running OS X 10.9.5. Virtualbox is at version 4.3.16. 

I am happy providing more information if needed.

**Comment by grossws** [comment]
@henrjk, what OS and kernel do you use in virtualbox? Can you say your `uname -a` and `cat /etc/*release*` from virtual machine running docker?

I'll create an issue now and create PR to fix it ASAP, but I don't know how fast it can be merged and build as official image.

**Comment by henrjk** [comment]
```
dev$ boot2docker ssh
                        ##        .
                  ## ## ##       ==
               ## ## ## ##      ===
           /""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
           \______ o          __/
             \    \        __/
              \____\______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
boot2docker: 1.3.0
             master : a083df4 - Thu Oct 16 17:05:03 UTC 2014
docker@boot2docker:~$ uname -a
Linux boot2docker 3.16.4-tinycore64 #1 SMP Tue Oct 14 01:10:32 UTC 2014 x86_64 GNU/Linux
docker@boot2docker:~$ cat /etc/*release*
NAME=Boot2Docker
VERSION=1.3.0
ID=boot2docker
ID_LIKE=tcl
VERSION_ID=1.3.0
PRETTY_NAME="Boot2Docker 1.3.0 (TCL 5.4); master : a083df4 - Thu Oct 16 17:05:03 UTC 2014"
ANSI_COLOR="1;34"
HOME_URL="http://boot2docker.io"
SUPPORT_URL="https://github.com/boot2docker/boot2docker"
BUG_REPORT_URL="https://github.com/boot2docker/boot2docker/issues"
docker@boot2docker:~$ docker ssh
```

**Comment by grossws** [comment]
As I see in [boot2docker kernel config](https://github.com/boot2docker/boot2docker/blob/5db7efbb4e0557f6efefdb56cb0263f80ed55834/kernel_config#L416) NUMA is disabled.

In any case, PR #15 is about to be merged, so it'll fix this image start on hosts without NUMA support.

**Comment by henrjk** [comment]
Build image 2.6 manually after checking out your fork and branch  `bug-start-on-non-numa-host`.

The image works for me. Thank you for the superbly fast turnaround.

**Pull request merged**
