### PR TITLE
add --auth option

### PR DESCRIPTION
**Pull request by 9cat**
add authentication parameter when start the mongod

### CODE REVIEW

**Comment by md5** [comment]
I think it would be better to add this to the documentation [here](https://github.com/docker-library/docs/blob/master/mongo/content.md#how-to-use-this-image) instead of changing the default behavior of the image, especially since it would be a breaking change for existing users.

For example:

> To start a mongo instance with authentication, pass the `--auth` flag.
> ```console
> docker run --name some-mongo -d mongo --auth
> ```

I'm also curious how this would actually work. Doesn't there need to be some user credentials added first? These docs seem to say that's the case: http://docs.mongodb.org/manual/tutorial/enable-authentication-without-bypass/#enable-authentication-after-creating-the-user-administrator

**Comment by md5** [comment]
From the aforementioned docs:

> In this procedure, you will create the instance’s first user, which must be a user administrator and then enable authentication. Then, you can authenticate as the user administrator to create additional users and grant additional access to the instance.

**Comment by md5** [comment]
There's also [this](http://docs.mongodb.org/manual/core/authentication/#localhost-exception):

> When active, the localhost exception allows connections from the localhost interface to create the first user on the admin database. The exception applies only when there are no users created in the MongoDB instance.

This would imply that in the Docker case, a user would have to use `docker exec` to create the users in order to have the connections come from localhost.

**Comment by tianon** [comment]
I agree with @md5 here; I don't understand the rationale for this being changed to be the default, especially since upstream doesn't ship with this as the default configuration.

**Comment by muikrad** [comment]
@md5 The information about how to setup the admin user is very scarce, I wasn't even aware that mongo --eval existed for this sort of purpose. A simple example of how to setup the first user should appear in the docs.

**Comment by md5** [comment]
@muikrad I don't see this being merged, so I'm not sure how relevant that would be. As for `mongo --eval`, it's pretty clearly documented in the "Mongo Scripting" docs: http://docs.mongodb.org/manual/tutorial/write-scripts-for-the-mongo-shell/#eval-option

**Comment by jjelev** [comment]
I there a way for a default configuration? I found two solutions, but they are not quite what I expected.

Simplest is from Tututm https://github.com/tutumcloud/mongodb/tree/master/2.6
They write a file in database volume folder if mongo is configurated and next time you build the image, they check this.

The more advanced soultution is from a japanese repo. https://github.com/dtanakax/docker-mongodb
But is really hard-core bash. I've never tested it but from what I saw It has many environment variables.
This should be the way mongo image to be built. MySQL image has environment variables and it's easy to set up.

**Comment by muikrad** [comment]
@md5 I know this pull request won't get merged - I'm not asking for added functionality around auth, i'm just saying that the documentation really should have a simple example about setting up auth:

1. Enable auth by launching ```docker run --name some-mongo -d mongo --auth```
2. Create the first user using ```docker exec some-mongo mongo --eval "db.getSiblingDB('admin').createUser({user: 'myAdminUser', pwd: 'myAdminPwd', roles:[{role:'userAdminAnyDatabase', db:'admin'}])"```
3. Then it's possible to connect to Mongo using 3rd party libraries and complete the setup using the API.

**Comment by md5** [comment]
@muikrad Got it.

It looks like the official image docs only have two instances of recommending `docker exec`:

1. `cassandra`: https://github.com/docker-library/docs/blob/master/cassandra/content.md#container-shell-access-and-viewing-cassandra-logs
2. `mysql`: https://github.com/docker-library/docs/blob/master/mysql/content.md#container-shell-access-and-viewing-mysql-logs

Both of those only talk about getting generic shell access inside the container, not about specific administrative tasks.

Notwithstanding what @tianon said earlier about `--auth` not being an explicit upstream recommendation, it seems that allowing an admin user to be created and configured via environment variables would be more in line with what the other database/storage engine images are doing.

**Comment by yosifkit** [comment]
@md5, The problem with creating users is the need for multiple processes. With the MySQL and Postgres images, it is already a bit of a hack to start up the respective daemons in the background with restrictions on where they are listening, then use the cli to pipe in SQL statements, then kill the daemon, and finally replace the shell with a newly started daemon in the foreground without the listening restrictions.  I am very hesitant to add this extra complexity to the mongo image.

@muikrad, I agree that this would be a good addition for the documentation; perhaps in the `Configuration` section?

**Comment by jayfk** [comment]
> I am very hesitant to add this extra complexity to the mongo image.

Which means the user has to add *this extra complexity* himself. That's maybe okay if you want to use the image as a single container on the CLI, but with tools like docker-compose it's not. It basically comes down to the problem that everyone who's using the image and wants authentication has to write his own hack.

**Pull request closed without merging**
