### PR TITLE
Add 3.0.0-rc6

### PR DESCRIPTION
**Pull request by davidau**
Adding 3.0.0-rc6 into new 3.0 folder.

### CODE REVIEW

**Comment by davidau** [comment]
Since [2.8 was renamed to 3.0](https://www.mongodb.com/blog/post/renaming-our-upcoming-release-mongodb-30) should the 2.8 folder be removed?

**Comment by md5** [comment]
@davidau that seems right! :+1:

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Comment by tianon** [comment]
Thanks for doing the legwork! :heart:

**Comment by tianon** [comment]
Arg:
```console
$ ./update.sh
+ '[' -z 2.2.7 ']'
+ sed -ri 's/^(ENV MONGO_VERSION) .*/\1 2.2.7/' 2.2/Dockerfile
+ sed -ri 's/^(ENV MONGO_RELEASE_FINGERPRINT) .*/\1 3AFEF01FE92B6927CC1EEC80F564179A36496327/' 2.2/Dockerfile
+ '[' -z 2.4.12 ']'
+ sed -ri 's/^(ENV MONGO_VERSION) .*/\1 2.4.12/' 2.4/Dockerfile
+ sed -ri 's/^(ENV MONGO_RELEASE_FINGERPRINT) .*/\1 CEA1E18DDA77EF4E67884FF2A6982D0160456C5A/' 2.4/Dockerfile
+ '[' -z 2.6.7 ']'
+ sed -ri 's/^(ENV MONGO_VERSION) .*/\1 2.6.7/' 2.6/Dockerfile
+ sed -ri 's/^(ENV MONGO_RELEASE_FINGERPRINT) .*/\1 DFFA3DCF326E302C4787673A01C4E7FAAAB2461C/' 2.6/Dockerfile
ERROR: missing GPG key fingerprint for 3.0; try:
  curl -sSL 'https://www.mongodb.org/static/pgp/server-3.0.asc' | gpg --with-fingerprint -
```

**Comment by tianon** [comment]
Looks like we just need to re-use 2.8's key.

**Comment by yosifkit** [comment]
Yeah, I figured since they just renamed the version, they would use the same key.

**Pull request merged**
