### PR TITLE
Account for more edge cases in entrypoint scripts

### PR DESCRIPTION
**Pull request by tianon**
Not sure what to do about `--config`, since that makes things a _lot_ more complicated to handle properly, but this at least allows users to still specify things like `--port` and not break initdb.

### CODE REVIEW

**Comment by yosifkit** [comment]
Not sure what to do about the users with a config file that specifies ssl key files but then we turn off ssl through the flags for the short init part and mongo fails to start.

They can work around it by skipping the entrypoint, but lose the init user creation and chown.

```console
$ docker run -d --user mongo --entrypoint mongod mongo:3.4 --config /path/to/mongo.conf
```

**Comment by tianon** [comment]
Yeah, I'm not sure either, especially since the config file is a really irritatingly structured YAML, hence `# TODO what do to about "--config" ? :(` in this PR :innocent: :disappointed:

**Comment by tianon** [comment]
(In other words, this is still better than what we've got now -- our alternative is to back out of the `initdb` behavior entirely, which is not great IMO)

**Comment by yosifkit** [comment]
I guess add a warning to the docs along with the new initialization variables and information.  We could also do versions that don't do initialization scripts or user creation?

**Comment by tianon** [comment]
Wouldn't that be easier to just add an environment variable for, or to show users how to use `--entrypoint` to skip our scripts entirely?

**Pull request merged**
